[package]
name = "merged-order-book-protos"
version = "0.1.0"
authors = ["Alex Butler <alexheretic@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
prost = "0.11.6"
tonic = "0.8.3"

[build-dependencies]
tonic-build = "0.8.4"
